---
- name: Check Oracle database Archivelog mode
  remote_user: oracle
  shell: >
    export ORACLE_SID={{pmon_status.stdout}};
    export ORACLE_HOME={{oracle_home}};
    export PATH={{path}};
    export TNS_ADMIN={{tns_admin}};
    {{oracle_home}}/bin/sqlplus -S /NOLOG @{{scripts_dir}}/db_log_mode.sql;
  register: log_mode

- name: Display Archivelog status 
  debug:
    msg: "Archivelog mode: {{log_mode.stdout}}"
#EOF