---
- name: Run opatch version
  become: yes
  become_user: "{{ oracle_owner }}"
  shell: >
    export ORACLE_HOME={{ oracle_home }}; 
    export PATH={{path}};
    ${ORACLE_HOME}/OPatch/opatch version;
  register: opatch_version

- name: Display opatch verion
  debug:
    msg: "opatch version is: {{ opatch_version.stdout }}"

