---
- name: List of database names on host
  shell: >
    cat /etc/oratab|grep {{ oracle_home }}|grep ':Y'|grep -v \*|cut -f1 -d':'
  register: dblist
  tags: datapatch
- debug:
    msg: "{{dblist.stdout_lines}}"
