---
- name: change ownership of oracle base, product, oradata, and FRA
  file:
    state: directory
    path: "{{ oracle_base }}"
    owner: "{{ oracle_owner }}"
    group: "{{ oracle_inst_grp }}"
    recurse: yes
  register: ora_base_dir

- name: create oracle db 19c home directory and change ownership
  file:
    state: directory
    path: "{{ oracle_home_19c }}"
    owner: "{{ oracle_owner }}"
    group: "{{ oracle_inst_grp }}"
    recurse: yes
  register: ora_home_dir

- name: create directory for oraInventory
  file:
    state: directory
    path: "{{ oracle_inventory }}"
    owner: "{{ oracle_owner }}"
    group: "{{ oracle_inst_grp }}"
    recurse: yes
  register: oraInv
#EOF
