---
- name: Copy file with owner and permissions
  template:
    src: dbora.j2
    dest: /etc/init.d/dbora
    owner: root
    group: dba
    mode: 0750
- name: create symbolic links rc0.d
  file:
    src: /etc/init.d/dbora
    dest: /etc/rc.d/rc0.d/K01dbora
    owner: root
    group: root
    state: link
- name: create symbolic links rc3.d
  file:
    src: /etc/init.d/dbora
    dest: /etc/rc.d/rc3.d/S99dbora
    owner: root
    group: root
    state: link
- name: create symbolic links rc5.d
  file:
    src: /etc/init.d/dbora
    dest: /etc/rc.d/rc5.d/S99dbora
    owner: root
    group: root
    state: link

