---
- name: update /etc/oratab for autostart
  tags: oratab
  replace:
    path: /etc/oratab
    regexp: '{{dbname}}:{{oracle_home_19c}}:N'
    replace: '{{dbname}}:{{oracle_home_19c}}:Y'
  register: oratab

- debug:
    var: oratab
