---
- name: create Audit Archive table
  become: yes
  become_user: oracle
  shell: >
    export ORACLE_SID={{loc_db_name}};
    export ORACLE_HOME={{oracle_home_19c}};
    export PATH={{path}};
    sqlplus -S /nolog @/home/oracle/scripts/audit_archive.sql
  
