---
# tasks file for oracle_db_install

- name: Copy db template files
  tags: db_templates
  include:
    copy_db_templates.yml

- name: Copy dbca response files
  tags: dbca_rsp
  include: 
    copy_dbca_19c_rsp.yml

- name: create database
  tags: createDB
  include:
    create_db_19c.yml
  register: dbstatus

#EOF
