---
- name: Create cron entry for auditarc.sh
  become: yes
  become_user: oracle
  cron:
    name: "Run auditarc.sh script"
    minute: "00"
    hour: "10"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/u01/home/oracle/scripts/auditarc.sh {{loc_db_name}} > /dev/null 2>&1"
