-- create audit_archive table as a copy of AUD$ table
set echo on
spool /home/oracle/scripts/logs/audit_archive.log
connect / as sysdba
create table system.audit_archive 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(
  INITIAL 16384 NEXT 16384  
  MINEXTENTS 1 MAXEXTENTS 2147483645  
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1  
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "ORA_AUDIT"
LOB ("SQLBIND") STORE AS BASICFILE (
  TABLESPACE "ORA_AUDIT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
LOB ("SQLTEXT") STORE AS BASICFILE (
  TABLESPACE "ORA_AUDIT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
PARTITION BY RANGE (NTIMESTAMP#)
  INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION AUD_STATIC_PART VALUES LESS THAN (TO_DATE('1-1-2022', 'DD-MM-YYYY'))
)
as select * from sys.aud$
where 1=2;
CREATE INDEX SYSTEM.AUD_ARCH_NTIMESTAMP_IDX 
        on SYSTEM.AUDIT_ARCHIVE (NTIMESTAMP#) 
        LOCAL tablespace ORA_AUDIT; 
 
CREATE INDEX SYSTEM.AUDIT_ARCHIVE_IDX01 
        on SYSTEM.AUDIT_ARCHIVE (SESSIONID,SES$TID) 
        LOCAL tablespace ORA_AUDIT; 
 
CREATE INDEX SYSTEM.AUDIT_ARCHIVE_IDX02 
        on SYSTEM.AUDIT_ARCHIVE (NTIMESTAMP#,USERID,ACTION#) 
        LOCAL tablespace ORA_AUDIT; 
spool off
exit
