-- Enable auditing
set echo on 
spool /home/oracle/scripts/logs/enable_audit.log
connect / as sysdba
AUDIT ALL BY ACCESS WHENEVER NOT SUCCESSFUL; 
AUDIT ALL ON SYS.AUD$ BY ACCESS; 
AUDIT ALTER SYSTEM; 
AUDIT SYSTEM AUDIT; 
AUDIT CREATE SESSION; 
AUDIT CREATE USER; 
AUDIT ALTER USER; 
AUDIT DROP USER; 
AUDIT ROLE; 
AUDIT CREATE ANY TABLE; 
AUDIT ALTER ANY TABLE; 
AUDIT DROP ANY TABLE; 
AUDIT CREATE PUBLIC DATABASE LINK; 
AUDIT GRANT ANY ROLE; 
AUDIT ALTER DATABASE; 
AUDIT CREATE ANY PROCEDURE; 
AUDIT ALTER ANY PROCEDURE; 
AUDIT DROP ANY PROCEDURE; 
AUDIT ALTER PROFILE; 
AUDIT DROP PROFILE; 
AUDIT GRANT ANY PRIVILEGE; 
AUDIT CREATE ANY LIBRARY; 
AUDIT EXEMPT ACCESS POLICY; 
AUDIT GRANT ANY OBJECT PRIVILEGE; 
AUDIT CREATE ANY JOB; 
AUDIT CREATE EXTERNAL JOB;
spool off
exit
