---
- name: include check_db_status.yml
  include:
    check_db_status.yml

- block:
    - name: Run Patch prereq CheckConflictAgainstOHWithDetail check
      become: yes
      become_user: "{{ oracle_owner }}"
      shell: >
        export ORACLE_HOME={{ oracle_home }};
        export PATH={{ path }};
        cd "{{ dbru_patch_dir }}/db_{{db_version}}_{{yyyy}}_{{qtr}}/{{patch_dir}}/{{item }}";
        opatch prereq CheckConflictAgainstOHWithDetail -ph ./
      loop:
        - "{{patchid1}}"
        - "{{patchid2}}"
        - "{{patchid3}}"
      register: ptch_prereq
#
    - name: Run Patch prereq CheckSystemSpace check
      become: yes
      become_user: "{{ oracle_owner }}"
      shell: >
        export ORACLE_HOME={{ oracle_home }};
        export PATH={{ path }};
        cd "{{ dbru_patch_dir }}/db_{{db_version}}_{{yyyy}}_{{qtr}}/{{patch_dir}}/{{item }}";
        opatch prereq CheckSystemSpace -ph ./
      loop:
        - "{{patchid1}}"
        - "{{patchid2}}"
        - "{{patchid3}}"
      register: ptch_prereq
#
    - name: Install Patch
      become: yes
      become_user: "{{ oracle_owner }}"
      shell: >
        export ORACLE_HOME={{ oracle_home }};
        export PATH={{ path }};
        cd "{{ dbru_patch_dir }}/db_{{db_version}}_{{yyyy}}_{{qtr}}/{{patch_dir}}/{{ item }}";
        opatch apply -silent -force -ocmrf {{ software_repo }}/ocm.rsp
      when:
        #- item.stdout.find('Prereq "checkConflictAgainstOHWithDetail" passed.') != -1
        #- item.stdout.find('Prereq "checkSystemSpace" passed.') != -1
        - ora_pmon.stdout=='' 
        - ora_listener.stdout=='' 
      loop:
        - "{{patchid1}}"
        - "{{patchid2}}"
        - "{{patchid3}}"
      register: patch_inst_results

#- name: Display results of Patch Install 
  #debug:
    #msg: "{{item.stdout_lines}}"
  #loop: "{{patch_inst_results.results}}"

#EOF
