---
- name: Check Oracle database open mode
  remote_user: oracle
  shell: >
    export ORACLE_SID={{db_name}};
    export ORACLE_HOME={{oracle_home}};
    export PATH={{path}};
    export TNS_ADMIN={{tns_admin}};
    {{oracle_home}}/bin/sqlplus -S /NOLOG @{{scripts_dir}}/db_open_mode.sql;
  register: oepn_mode
  when:
    pmon_status.stdout != ""

- name: Display open mode 
  debug:
    msg: "open mode: {{oepn_mode.stdout}}"
#EOF