---
- name: Run Oracle Preinstall RPM
  yum:
    name: oracle-database-preinstall-19c
    state: present
  register:
    db_preinst_19c

- name: Add users to group vboxsf
  user:
    name: oracle
    groups: vboxsf
    append: yes

- name: Set Oracle user password
  tags: orapass
  shell: >
    echo "{{oracle_pass}}"|passwd oracle --stdin

- name: copy ssh keys to oracle user
  tags: sshkey
  authorized_key:
    user: oracle
    key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"

- name: check hugepagesize (default is 2048KB)
  shell: >
    export PATH={{path}};
    grep Hugepagesize /proc/meminfo|cut -f2 -d":";
  register: hugepagesize
- debug:
    msg: "{{hugepagesize.stdout|trim}}"

- name: set system hugepages
  lineinfile:
    path: /etc/sysctl.conf
    line: |
      # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      # (from 'grep -i hugepagesize /proc/meminfo' output) Hugepagesize: "{{hugepagesize.stdout|trim}}"
      # (from 'free -m' output) RAM = {{ansible_memtotal_mb}} MB
      # Reserving 60% of physical memory for Oracle Database SGA
      # {{ansible_memtotal_mb}} MB x .6 = {{ (ansible_memtotal_mb * 0.6) | round | int }} 
      # devide the above number by 2 MB - hugepage size
      # {{ansible_memtotal_mb}}*.06/2+5 = {{ (ansible_memtotal_mb*0.6/2+5) | round | int }} huge pages
      # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      vm.nr_hugepages = {{ (ansible_memtotal_mb*0.6/2+5) | round | int }}

- name: run sysctl -p
  shell: >
    sysctl -p;

#EOF
