---
- name: unzip oracle 19c db software
  unarchive:
    src: "{{ oracle_db_19c_oct2021_zip }}"
    dest: /
    remote_src : yes
    owner: "{{ oracle_owner }}"
    group: "{{ oracle_inst_grp }}"
  register: unzip_bin

#EOF
